### ISSUE TITLE
Generating local parameters

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-ice#6]
When does the RTCIceTransport generate its local parameters (ufrag/pwd)?

Ideas:
* At creation time. This means getLocalParameters() will never return null (it's allowed to in the WebRTC-PC specification).
* Regenerate them every time gather() is called after the first time.

**Comment by aboba** [comment]
In ORTC `getLocalParameters()` never returns `null` (the specification doesn't say whether the local parameters are generated when the `RTCIceGatherer` is constructed or when `getLocalParameters` is called). 

We should probably discuss what happens when `gather()` is called multiple times in a separate issue.
